spring:
  cloud:
    gateway:
      routes:
        - id  : swiggy-service
          uri : lb://SWIGGY-SERVICE
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter 
          
        - id : restaurant-service
          uri : lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter
            
        - id : auth-service
          uri : lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
         
       